Restructure volume C and B
usnistgov/800-63-ImplResourceCenter pull request #2
Opened 2018-05-31 20:05 UTC by jricher

Add page headers to volume C and B, add links to C and B pages to sidebar.

2018-05-31 23:30 UTC, jimfenton requested changes
close...

2018-05-31 23:30 UTC, jimfenton commented on _includes/sidenav.html
> +      <a href="{{ site.baseurl }}/63B/SampleAuthenticators">Sample Authenticators</a>
Do these new links need to be enclosed inside a
    ```<li class="dropdown-item">  </li>```
like the 63C sections are?

2018-05-31 23:30 UTC, jimfenton commented on _includes/sidenav.html
> +    <li class="dowpdown-item">
dowpdown -> dropdown

2018-06-01 16:43 UTC, jricher commented
Good catch, fixed both of those. Note that the sidebar doesn't have the expand/collapse functionality yet so it goes off screen, but that needs to be added regardless.

2018-06-01 16:44 UTC, jimfenton approved these changes

2018-06-01 16:44 UTC, merged